# SPDX-FileCopyrightText: 2023 Sidings Media
# SPDX-License-Identifier: CC0-1.0

version: "3.9"
services:
  <service>:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TRUSTED_PROXIES=${TRUSTED_PROXIES:-*}
      - GIN_MODE=${GIN_MODE:-release}
